"""PyMOL PML script generation utilities.

Generates PyMOL command scripts (.pml) for visual inspection of docked poses.
No PyMOL installation is required — this module only produces text files.

All file paths written into PML scripts are **relative** to the directory
containing the output PML file so that the script is portable across
different machines and container environments.

Example::

    write_ranked_poses_pml(
        poses_sdf="results/ranked_poses.sdf",
        protein_pdb="receptor/6x1a_clean.pdb",
        output_pml="pymol/ranked_top10.pml",
        max_poses=10,
    )

    write_reference_overlay_pml(
        selected_sdf="results/selected.sdf",
        reference_sdf="reference/co_crystal.sdf",
        protein_pdb="receptor/6x1a_clean.pdb",
        output_pml="pymol/overlay.pml",
    )
"""

from __future__ import annotations

from pathlib import Path

from rdkit import Chem


# ---------------------------------------------------------------------------
# Path helper
# ---------------------------------------------------------------------------


def to_relative_path(path: str | Path, base_dir: str | Path) -> Path:
    """Return *path* as a relative path from *base_dir*.

    If *path* cannot be expressed relative to *base_dir* (e.g., different
    Windows drive letters), the original absolute path is returned unchanged.

    Parameters
    ----------
    path:
        Target file path to convert.
    base_dir:
        Directory to compute the relative path from.

    Returns
    -------
    Path
        Relative path, or absolute path as a fallback.
    """
    path = Path(path).resolve()
    base_dir = Path(base_dir).resolve()
    try:
        # walk_up=True (Python 3.12+) allows "../" style relative paths
        return path.relative_to(base_dir, walk_up=True)
    except ValueError:
        return path


# ---------------------------------------------------------------------------
# Colour palette helpers
# ---------------------------------------------------------------------------

_DEFAULT_RANK_COLORS = [
    "tv_red", "tv_orange", "tv_yellow", "tv_green", "tv_blue",
    "tv_violet", "pink", "cyan", "magenta", "white",
]

_DEFAULT_TIER_COLORS = {
    "A": "tv_red",
    "B": "tv_orange",
    "C": "tv_yellow",
    "D": "tv_green",
    "reference": "grey70",
}


# ---------------------------------------------------------------------------
# PML generators
# ---------------------------------------------------------------------------


def write_ranked_poses_pml(
    poses_sdf: str | Path,
    protein_pdb: str | Path,
    output_pml: str | Path,
    rank_col: str | None = None,
    max_poses: int = 10,
    color_scheme: list[str] | None = None,
    show_protein: bool = True,
) -> Path:
    """Generate a PyMOL script that loads and colour-codes ranked docked poses.

    Poses are loaded in rank order (ascending by *rank_col* if provided,
    otherwise in SDF file order).  Each pose receives a distinct colour from
    *color_scheme*.  The protein is shown as a grey cartoon.

    Parameters
    ----------
    poses_sdf:
        SDF file containing docked poses.  Each molecule should carry a
        ``mol_name`` or ``_Name`` property used as the PyMOL object name.
    protein_pdb:
        Receptor PDB file.
    output_pml:
        Destination ``.pml`` file.  Parent directories are created if absent.
    rank_col:
        SDF property name used to sort poses (ascending).  ``None`` preserves
        SDF file order.
    max_poses:
        Maximum number of poses to include in the script.
    color_scheme:
        List of PyMOL colour names, one per pose.  Defaults to a 10-colour
        palette cycling from red to white.
    show_protein:
        If ``True``, load and display the protein as a grey cartoon.

    Returns
    -------
    Path
        Absolute path to the written PML file.
    """
    output_pml = Path(output_pml).resolve()
    output_pml.parent.mkdir(parents=True, exist_ok=True)
    base_dir = output_pml.parent

    if color_scheme is None:
        color_scheme = _DEFAULT_RANK_COLORS

    # Read and optionally sort poses
    supplier = Chem.SDMolSupplier(str(poses_sdf), removeHs=False, sanitize=False)
    mols = [m for m in supplier if m is not None]

    if rank_col is not None:
        def _rank_key(m):
            v = m.GetPropsAsDict().get(rank_col)
            try:
                return float(v)
            except (TypeError, ValueError):
                return float("inf")
        mols = sorted(mols, key=_rank_key)

    mols = mols[:max_poses]

    lines: list[str] = [
        "# PyMOL script — ranked docked poses",
        "# Generated by mdatools.docking.visualization.pymol",
        "",
        "bg_color white",
        "set cartoon_fancy_helices, 1",
        "set stick_radius, 0.15",
        "",
    ]

    if show_protein:
        pdb_rel = to_relative_path(protein_pdb, base_dir)
        lines += [
            f"load {pdb_rel}, protein",
            "hide everything, protein",
            "show cartoon, protein",
            "color grey80, protein",
            "",
        ]

    for i, mol in enumerate(mols):
        props = mol.GetPropsAsDict()
        name = (
            props.get("mol_name")
            or props.get("_Name")
            or mol.GetProp("_Name") if mol.HasProp("_Name") else None
            or f"pose_{i + 1:03d}"
        )
        # Sanitise PyMOL object name (no spaces / slashes)
        obj_name = str(name).replace(" ", "_").replace("/", "_").replace("\\", "_")

        color = color_scheme[i % len(color_scheme)]

        # Write individual SDF for this pose
        pose_sdf_name = f"{obj_name}.sdf"
        pose_sdf_path = output_pml.parent / pose_sdf_name
        writer = Chem.SDWriter(str(pose_sdf_path))
        writer.write(mol)
        writer.close()

        pose_rel = to_relative_path(pose_sdf_path, base_dir)
        lines += [
            f"load {pose_rel}, {obj_name}",
            f"show sticks, {obj_name}",
            f"color {color}, {obj_name}",
            "",
        ]

    lines += [
        "zoom all",
        "ray 1200, 900",
    ]

    output_pml.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_pml


def write_reference_overlay_pml(
    selected_sdf: str | Path,
    reference_sdf: str | Path,
    protein_pdb: str | Path,
    output_pml: str | Path,
    tier_col: str | None = None,
    tier_colors: dict[str, str] | None = None,
    show_protein: bool = True,
) -> Path:
    """Generate a PyMOL script overlaying selected poses with a reference ligand.

    Selected poses are colour-coded by their *tier_col* property value (e.g.,
    ``"Mode A"``, ``"Mode B"``).  The reference ligand is shown in a neutral
    grey.

    Parameters
    ----------
    selected_sdf:
        SDF file of selected/ranked poses.
    reference_sdf:
        SDF file of the reference ligand(s) (co-crystal or MCS template).
    protein_pdb:
        Receptor PDB file.
    output_pml:
        Destination ``.pml`` file.  Parent directories are created if absent.
    tier_col:
        SDF property name used for colour grouping.  ``None`` uses a single
        colour for all selected poses.
    tier_colors:
        Mapping of tier label → PyMOL colour name.  Defaults to a small
        built-in palette (A→red, B→orange, C→yellow, D→green).
        The key ``"reference"`` controls the reference ligand colour.
    show_protein:
        If ``True``, load and display the protein as a grey cartoon.

    Returns
    -------
    Path
        Absolute path to the written PML file.
    """
    output_pml = Path(output_pml).resolve()
    output_pml.parent.mkdir(parents=True, exist_ok=True)
    base_dir = output_pml.parent

    colors = dict(_DEFAULT_TIER_COLORS)
    if tier_colors:
        colors.update(tier_colors)

    lines: list[str] = [
        "# PyMOL script — reference overlay",
        "# Generated by mdatools.docking.visualization.pymol",
        "",
        "bg_color white",
        "set cartoon_fancy_helices, 1",
        "set stick_radius, 0.15",
        "",
    ]

    if show_protein:
        pdb_rel = to_relative_path(protein_pdb, base_dir)
        lines += [
            f"load {pdb_rel}, protein",
            "hide everything, protein",
            "show cartoon, protein",
            "color grey80, protein",
            "",
        ]

    # Reference ligand(s)
    ref_supplier = Chem.SDMolSupplier(str(reference_sdf), removeHs=False, sanitize=False)
    ref_mols = [m for m in ref_supplier if m is not None]
    for i, mol in enumerate(ref_mols):
        props = mol.GetPropsAsDict()
        name = (
            props.get("mol_name")
            or (mol.GetProp("_Name") if mol.HasProp("_Name") else None)
            or f"reference_{i + 1:03d}"
        )
        obj_name = f"ref_{str(name).replace(' ', '_')}"
        ref_color = colors.get("reference", "grey70")

        pose_sdf_name = f"{obj_name}.sdf"
        pose_sdf_path = output_pml.parent / pose_sdf_name
        writer = Chem.SDWriter(str(pose_sdf_path))
        writer.write(mol)
        writer.close()

        rel = to_relative_path(pose_sdf_path, base_dir)
        lines += [
            f"load {rel}, {obj_name}",
            f"show sticks, {obj_name}",
            f"color {ref_color}, {obj_name}",
            "",
        ]

    # Selected poses
    sel_supplier = Chem.SDMolSupplier(str(selected_sdf), removeHs=False, sanitize=False)
    sel_mols = [m for m in sel_supplier if m is not None]

    # Group by tier for consolidated colour commands
    tier_groups: dict[str, list[str]] = {}

    for i, mol in enumerate(sel_mols):
        props = mol.GetPropsAsDict()
        name = (
            props.get("mol_name")
            or (mol.GetProp("_Name") if mol.HasProp("_Name") else None)
            or f"pose_{i + 1:03d}"
        )
        obj_name = str(name).replace(" ", "_").replace("/", "_")

        tier = str(props.get(tier_col, "A")) if tier_col and tier_col in props else "A"
        tier_groups.setdefault(tier, []).append(obj_name)

        pose_sdf_name = f"{obj_name}.sdf"
        pose_sdf_path = output_pml.parent / pose_sdf_name
        writer = Chem.SDWriter(str(pose_sdf_path))
        writer.write(mol)
        writer.close()

        rel = to_relative_path(pose_sdf_path, base_dir)
        lines += [
            f"load {rel}, {obj_name}",
            f"show sticks, {obj_name}",
        ]

    lines.append("")

    # Apply tier colours in bulk
    for tier, obj_names in tier_groups.items():
        color = colors.get(tier, "tv_blue")
        sel_str = " or ".join(obj_names)
        lines.append(f"color {color}, {sel_str}")

    lines += [
        "",
        "zoom all",
        "ray 1200, 900",
    ]

    output_pml.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_pml
