"""Pure-function PML script builders (no PyMOL import needed for tests)."""

from __future__ import annotations

from pathlib import Path


def build_dihedral_pml(
    pse_path: Path | str,
    output_csv: Path | str,
    ligand_resname: str,
    dihedral_defs: list[tuple[str, str, str, str, str]],
    object_name: str = "traj",
) -> str:
    """Build a PML script string that extracts dihedral angles to CSV.

    Parameters
    ----------
    pse_path:
        Path to the .pse file.
    output_csv:
        Destination CSV path.
    ligand_resname:
        Residue name of the ligand.
    dihedral_defs:
        List of ``(label, a1, a2, a3, a4)`` tuples.
    object_name:
        Name of the trajectory object in PyMOL.
    """
    defs_repr = repr(dihedral_defs)
    return f"""\
# Auto-generated by mdatools.pymol_bridge.pml_builder
load {pse_path}
disable all
enable {object_name}

python
import csv, math
import numpy as np

OUT_CSV = r"{output_csv}"
RESNAME = "{ligand_resname}"
OBJ = "{object_name}"

DIHEDRALS = {defs_repr}

def get_dihedral(state, a1, a2, a3, a4):
    sels = [f"{{OBJ}} and resname {{RESNAME}} and name {{a}}" for a in (a1, a2, a3, a4)]
    coords = []
    for s in sels:
        c = cmd.get_coords(s, state=state)
        if c is None or len(c) == 0:
            return float('nan')
        coords.append(c[0])
    p1, p2, p3, p4 = [np.array(c) for c in coords]
    b1 = p2 - p1; b2 = p3 - p2; b3 = p4 - p3
    n1 = np.cross(b1, b2); n2 = np.cross(b2, b3)
    ln1, ln2 = np.linalg.norm(n1), np.linalg.norm(n2)
    if ln1 < 1e-6 or ln2 < 1e-6:
        return float('nan')
    n1 /= ln1; n2 /= ln2
    cos_a = float(np.clip(np.dot(n1, n2), -1.0, 1.0))
    angle = math.degrees(math.acos(cos_a))
    if np.dot(np.cross(n1, n2), b2) < 0:
        angle = -angle
    return angle

n_states = cmd.count_states(OBJ)
rows = []
for i in range(1, n_states + 1):
    row = [i - 1]
    for label, a1, a2, a3, a4 in DIHEDRALS:
        ang = get_dihedral(i, a1, a2, a3, a4)
        row.append(round(ang, 3) if not math.isnan(ang) else float('nan'))
    rows.append(row)

headers = ["frame"] + [d[0] for d in DIHEDRALS]
with open(OUT_CSV, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(headers)
    w.writerows(rows)

python end
quit
"""


def build_frame_export_pml(
    pse_path: Path | str,
    output_dir: Path | str,
    prefix: str,
    *,
    max_frames: int = 100,
    step: int = 1,
    object_name: str = "traj",
    remove_resnames: list[str] | None = None,
    skip_existing: bool = True,
) -> str:
    """Build a PML script that exports every *step*-th frame as a PDB.

    Solvent and ions listed in *remove_resnames* are stripped before saving
    so that PoseBusters receives clean protein + ligand structures.

    Parameters
    ----------
    pse_path:
        Path to the .pse session file.
    output_dir:
        Directory to write frame PDBs.
    prefix:
        Filename prefix, e.g. ``"snapshot_run01"``.
    max_frames:
        Maximum number of frames to export.
    step:
        Export every *step*-th state.
    object_name:
        PyMOL trajectory object name.
    remove_resnames:
        Residue names to strip (solvent / ions).
    skip_existing:
        Skip frames whose output PDB already exists.
    """
    _default_remove = [
        "HOH", "WAT", "SOL", "TIP", "TIP3", "TIP4",
        "NA", "CL", "K", "CA", "MG", "ZN", "FE", "MN", "CU", "CO", "NI",
        "SO4", "PO4", "GOL", "EDO", "PEG", "DMS", "ACE", "ACT",
    ]
    remove = remove_resnames if remove_resnames is not None else _default_remove
    remove_repr = repr(remove)

    return f"""\
# Auto-generated by mdatools.pymol_bridge.pml_builder.build_frame_export_pml
load {pse_path}
disable all
enable {object_name}

python
from pathlib import Path

OUT_DIR   = Path(r"{output_dir}")
PREFIX    = "{prefix}"
OBJ       = "{object_name}"
MAX_FRAMES   = {max_frames}
STEP         = {step}
SKIP_EXISTING = {skip_existing}
REMOVE_RES = {remove_repr}

OUT_DIR.mkdir(parents=True, exist_ok=True)

remove_sel = " or ".join(f"resn {{r}}" for r in REMOVE_RES)
cmd.remove(remove_sel)

n_states = cmd.count_states(OBJ)
n_export = min(n_states, MAX_FRAMES * STEP)
exported = 0
for state in range(1, n_export + 1, STEP):
    frame_idx = state - 1
    out_path = OUT_DIR / f"{{PREFIX}}_frame{{frame_idx:04d}}.pdb"
    if SKIP_EXISTING and out_path.exists():
        exported += 1
        continue
    cmd.save(str(out_path), OBJ, state=state)
    exported += 1
    if frame_idx % 10 == 0:
        print(f"[PROGRESS] frame {{frame_idx}}/{{n_export - 1}}", flush=True)
    if exported >= MAX_FRAMES:
        break

print(f"[DONE] {{exported}} frames -> {{OUT_DIR}}", flush=True)

python end
quit
"""


_DEFAULT_REMOVE_RESNAMES: list[str] = [
    "HOH", "WAT", "SOL", "TIP", "TIP3", "TIP4",
    "NA", "CL", "K", "CA", "MG", "ZN", "FE", "MN", "CU", "CO", "NI",
    "SO4", "PO4", "GOL", "EDO", "PEG", "DMS", "ACE", "ACT",
]


def build_clean_snapshot_pml(
    input_pdbs: list[Path | str],
    output_dir: Path | str,
    ligand_resname: str = "UNK",
    remove_resnames: list[str] | None = None,
) -> str:
    """Build a PML script that strips solvent/ions from snapshot PDBs.

    For each PDB in *input_pdbs* the script:
    1. Loads the file into a named object.
    2. Removes all residues whose names are in *remove_resnames*.
    3. Saves a ``<stem>_clean.pdb`` into *output_dir*.
    4. Deletes the object to free memory.

    Parameters
    ----------
    input_pdbs:
        List of PDB paths to clean.
    output_dir:
        Directory to write cleaned PDBs.
    ligand_resname:
        Residue name of the ligand — kept together with ``polymer``.
    remove_resnames:
        Residue names to strip.  Defaults to water, common ions, and
        crystallographic additives.

    Returns
    -------
    PML script string (pass to ``pymol -c``).
    """
    remove = remove_resnames if remove_resnames is not None else _DEFAULT_REMOVE_RESNAMES
    remove_repr = repr(remove)
    input_repr = repr([str(p) for p in input_pdbs])

    return f"""\
# Auto-generated by mdatools.pymol_bridge.pml_builder.build_clean_snapshot_pml
python
from pathlib import Path

INPUT_PDBS   = {input_repr}
OUTPUT_DIR   = Path(r"{output_dir}")
REMOVE_RES   = {remove_repr}

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
remove_sel = " or ".join(f"resn {{r}}" for r in REMOVE_RES)

for pdb_str in INPUT_PDBS:
    pdb = Path(pdb_str)
    obj = pdb.stem.replace("-", "_").replace(".", "_")
    cmd.load(str(pdb), obj)
    cmd.remove(f"{{obj}} and ({{remove_sel}})")
    out = OUTPUT_DIR / (pdb.stem + "_clean.pdb")
    cmd.save(str(out), obj)
    cmd.delete(obj)

print("[DONE] cleaned {{}} snapshots -> {{}}".format(len(INPUT_PDBS), OUTPUT_DIR), flush=True)

python end
quit
"""


def build_validation_pml(
    pse_path: Path | str,
    output_csv: Path | str,
    pocket_resids: list[int],
    hbond_pairs: list[tuple[str, str]],
    extra_pairs: list[tuple[str, str]] | None = None,
    object_name: str = "traj",
    ligand_resname: str = "UNK",
) -> str:
    """Build a PML script that extracts per-frame RMSD and distance metrics.

    Parameters
    ----------
    pocket_resids:
        Residue IDs defining the binding pocket (for pocket RMSD).
    hbond_pairs:
        List of ``(sel1, sel2)`` atom selection strings for distance
        measurement.  e.g. ``("resi 150 and name OD1", "resname UNK and name N1")``.
    extra_pairs:
        Additional distance pairs beyond the primary H-bond.
    object_name:
        PyMOL object name.
    """
    extra_pairs = extra_pairs or []
    all_pairs = hbond_pairs + extra_pairs
    pairs_repr = repr(all_pairs)
    pocket_sel = "+".join(str(r) for r in pocket_resids)

    return f"""\
# Auto-generated by mdatools.pymol_bridge.pml_builder
load {pse_path}
disable all
enable {object_name}

python
import csv
import numpy as np

OUT_CSV = r"{output_csv}"
OBJ = "{object_name}"
POCKET_SEL = "{{OBJ}} and polymer and resi {pocket_sel} and name CA"
GLOBAL_SEL = "{{OBJ}} and polymer and name CA"
PAIRS = {pairs_repr}

def rmsd(a, b):
    if a is None or b is None or len(a) != len(b) or len(a) == 0:
        return float('nan')
    return float(np.sqrt(((a - b) ** 2).sum(axis=1).mean()))

def get_dist(s1, s2, state):
    try:
        return float(cmd.get_distance(s1, s2, state=state))
    except Exception:
        return float('nan')

ref_global = cmd.get_coords(GLOBAL_SEL.format(OBJ=OBJ), state=1)
ref_pocket = cmd.get_coords(POCKET_SEL.format(OBJ=OBJ), state=1)

n_states = cmd.count_states(OBJ)
headers = ["frame", "rmsd_global", "rmsd_pocket"] + [
    f"dist_{{i}}" for i in range(len(PAIRS))
]
rows = []
for i in range(1, n_states + 1):
    curr_g = cmd.get_coords(GLOBAL_SEL.format(OBJ=OBJ), state=i)
    curr_p = cmd.get_coords(POCKET_SEL.format(OBJ=OBJ), state=i)
    row = [i - 1, rmsd(curr_g, ref_global), rmsd(curr_p, ref_pocket)]
    for s1, s2 in PAIRS:
        row.append(get_dist(
            f"{{OBJ}} and {{s1}}", f"{{OBJ}} and {{s2}}", i
        ))
    rows.append(row)

with open(OUT_CSV, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(headers)
    w.writerows(rows)

python end
quit
"""
